Update WordPress Dockerfile and add configuration script for setup automation

diff --git a/src/requirements/WordPress/Dockerfile b/src/requirements/WordPress/Dockerfile
--- a/src/requirements/WordPress/Dockerfile
+++ b/src/requirements/WordPress/Dockerfile
@@ -1,11 +1,13 @@
 FROM alpine:3.19
 
-RUN (apk add --no-cache wordpress php-fpm php-mysqli tini && \
+RUN (apk add --no-cache php83-fpm php83-mysqli tini && \
 	mkdir -p /var/www/html && \
 	chown -R nobody:nobody /var/www/html) || \
-	(echo "Failed to install WordPress" >&2 ; exit 1)
+	(echo "Failed to install dependencies" >&2 ; exit 1)
 
 EXPOSE 9000
+
+WORKDIR /var/www/html
 
 ENTRYPOINT [ "/sbin/tini", "--" ]
 
