Fix order
Script cant use secrets at buildtime

diff --git a/src/requirements/MariaDB/Dockerfile b/src/requirements/MariaDB/Dockerfile
--- a/src/requirements/MariaDB/Dockerfile
+++ b/src/requirements/MariaDB/Dockerfile
@@ -2,22 +2,20 @@ FROM alpine:3.19
 
 COPY config_db.sh /tmp/config_db.sh
 
-RUN (apk add --no-cache mariadb tini && \
+VOLUME [ "/var/lib/mysql" ]
+
+RUN (apk add --no-cache mariadb mariadb-client tini && \
 	mkdir -p /var/lib/mysql && \
 	chown -R mysql:mysql /var/lib/mysql) || \
 	(echo "Failed to install MariaDB" >&2 ; exit 1) && \
 	(mysql_install_db --user=mysql --datadir=/var/lib/mysql && \
-	chmod +x /tmp/config_db.sh && \
-	/tmp/config_db.sh; \
-	rm /tmp/config_db.sh) || \
-	(echo "Failed to configure MariaDB" >&2 ; exit 1)
+	chmod +x /tmp/config_db.sh) || \
+	(echo "Failed to prepare script for MariaDB" >&2 ; exit 1)
 
-VOLUME [ "/var/lib/mysql" ]
-
-HEALTHCHECK CMD ["mysqladmin", "ping", "--silent"]
+HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 CMD ["mysqladmin", "ping", "--silent"]
 
 EXPOSE 3306
 
-ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/mysqld_safe"]
+ENTRYPOINT ["/sbin/tini", "--"]
 
-CMD ["--datadir=/var/lib/mysql"]
+CMD ["/tmp/config_db.sh"]
